packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": "22.18.1"
  "@types/react": "19.0.8"
  "@types/react-dom": "19.0.3"
  "@tanstack/react-query": "5.87.4"
  typescript: "5.5.4"
  viem: "2.29.2"
  wagmi: "2.16.9"
  react: "19.1.1"
  react-dom: "19.1.1"
  "icon-sdk-js": "1.5.3"
  "@vitest/coverage-v8": "3.2.4"
  "tsup": "8.5.0"
  "@changesets/cli": "2.29.7"
  "@arethetypeswrong/cli": "0.17.4"
  "vitest": "3.2.4"
  "bignumber.js": "9.3.1"
  "@mysten/sui": "1.21.2"
  "@mysten/wallet-standard": "0.15.6"
  "@mysten/dapp-kit": "0.14.18"
  "@stellar/stellar-sdk": "15.1.0"
  "@injectivelabs/sdk-ts": "1.18.14"
  "@injectivelabs/networks": "1.18.14"
  "@injectivelabs/ts-types": "1.18.14"
  "@injectivelabs/wallet-base": "1.18.14"
  "@injectivelabs/wallet-core": "1.18.14"
  "@injectivelabs/wallet-strategy": "1.18.14"
  "@injectivelabs/wallet-evm": "1.18.14"
  "@injectivelabs/wallet-cosmos": "1.18.14"
  "@solana/spl-token": "0.4.9"
  "@solana/wallet-adapter-base": "0.9.26"
  "@solana/web3.js": "1.98.0"
  "@stacks/transactions": "7.3.1"
  "@stacks/network": "7.3.1"
  "@stacks/connect": "8.2.6"
  "near-api-js": "7.2.0"
  "madge": "8.0.0"
  "knip": "5.30.5"
  "tslib": "2.8.1"
