name: Publish @sodax/wallet-sdk-react Package to npmjs

on:
  push:
    tags:
      - '@sodax/wallet-sdk-react@*.*.*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.32.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Packages
        run: pnpm turbo run build --filter=@sodax/wallet-sdk-react...
      - name: Publish package
        run: |
          cd packages/wallet-sdk-react
          pnpm publish --no-git-checks --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.SODAX_SDKS_NPM_PUBLISH_TOKEN}}